columns:
  - name: id
    type: integer
    attribute: primary_key

  - name: name
    type: string

  - name: in_date
    type: date

  - name: department
    type: string

  - name: position
    type: string
